### ISSUE TITLE
Activating the env doesn't work in install script

### ISSUE THREAD

**Issue by tayabsoomro** [coadunate/MICAS#26]
The code responsible for activating the env after creating it does not work and it is required for subsequent step.

https://github.com/coadunate/MICAS/blob/master/install.sh#L59-L72

**Comment by tayabsoomro** [comment]
Possible solution:

```sh
# run this before the conda activate command
eval "$(command conda 'shell.bash' 'hook' 2> /dev/null)"
```

**Comment by syncrotron** [comment]
We decided that we will have the startup script and manual instructions include a blurb about starting the virtual environment
