### ISSUE TITLE
Install script need to be a little more sophisticated

### ISSUE THREAD

**Issue by tayabsoomro** [coadunate/MICAS#31]
It keeps downloading the tarballs. It would be nice to check if they already exists and only download if they don't.

**Comment by syncrotron** [comment]
Made some headway cleaning this up in [this dev branch](https://github.com/coadunate/MICAS/tree/31-update-install.sh). Mainly, I removed the repetitive downloading of tar balls, and streamlined it immediately unpack the tars. Other than that, the script is far tidier and easy to read (at least to me)

**Comment by syncrotron** [comment]
Did some more work on the cleaning up of the install.sh and created a start.sh. Still very experimental but its a good start.

**Comment by syncrotron** [comment]
Install script has now taken a backseat to the dockerfile, and thus "sophistication" is no longer required within the install script
