### ISSUE TITLE
Remove dependency on Tayabs email for Entrez.email

### ISSUE THREAD

**Issue by syncrotron** [coadunate/MICAS#50]
In the crusade to remove magic numbers, I propose we move the hard coded `Entrez.email` in [Tasks.py](https://github.com/coadunate/MICAS/blob/f7f0070f5bc6ef33e17c5bd36a20fdd52c04e3b1/server/app/main/utils/tasks.py#L11) to a config file or user settable parameter.

**Comment by tayabsoomro** [comment]
This has been removed entirely since we are not incorporating Sankey visualization in this current release. We will re-visit this once we have to deal with this again. Closed.
