### ISSUE TITLE
Run_fastq_watcher needs to run in background.

### ISSUE THREAD

**Issue by syncrotron** [coadunate/MICAS#60]
Currently, run_fastq_watcher does not run in the background, thus whenever the page is reloaded the watcher dies. We need to have run_fastq_watcher run in the background.

**Comment by tayabsoomro** [comment]
![image](https://user-images.githubusercontent.com/19979068/148143018-2f010219-4ab6-4449-b1cd-82b507e75583.png)

**Comment by syncrotron** [comment]
This was resolved in one of the monolithic "Lots of changes" commit
