### ISSUE TITLE
final.out.paf file not being created with simulation

### ISSUE THREAD

**Issue by tayabsoomro** [coadunate/MICAS#64]
As per one of the simulation test run by @syncrotron, the `final.out.paf` file was not generated and the individual `.*.1.out.paf` files were not removed. [This](https://github.com/coadunate/MICAS/blob/master/server/app/main/utils/FASTQFileHandler.py#L94-L110) is the piece of code responsible for concatenating the individual PAF files into `final.out.paf`.

**Comment by syncrotron** [comment]
This error has since been resolved. Due to poor commit message, the actual commit this was resolved in is lost to time.
